# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(443, 221)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(8, -1, 431, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_2.addWidget(self.startButton)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("QLabel{\n"
"background-color: rgb(0, 255, 0);\n"
"border-radius: 30px\n"
"}\n"
"QLabel:disabled{\n"
"     background-color:lightgrey;\n"
"    color: rgba(216, 217, 218,0);\n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comBox.sizePolicy().hasHeightForWidth())
        self.comBox.setSizePolicy(sizePolicy)
        self.comBox.setObjectName("comBox")
        self.horizontalLayout_4.addWidget(self.comBox)
        self.openPortButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openPortButton.sizePolicy().hasHeightForWidth())
        self.openPortButton.setSizePolicy(sizePolicy)
        self.openPortButton.setObjectName("openPortButton")
        self.horizontalLayout_4.addWidget(self.openPortButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.testButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.testButton.setObjectName("testButton")
        self.verticalLayout.addWidget(self.testButton)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.editFolderPath = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editFolderPath.sizePolicy().hasHeightForWidth())
        self.editFolderPath.setSizePolicy(sizePolicy)
        self.editFolderPath.setObjectName("editFolderPath")
        self.horizontalLayout.addWidget(self.editFolderPath)
        self.folderPath = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.folderPath.setObjectName("folderPath")
        self.horizontalLayout.addWidget(self.folderPath)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.status = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.status.setEnabled(False)
        self.status.setStyleSheet("QLabel{\n"
"background-color: rgb(0, 255, 0);\n"
"border-radius: 10px\n"
"}\n"
"QLabel:disabled{\n"
"     background-color:rgba(0, 0, 0, 0);\n"
"    color: rgba(216, 217, 218,0);\n"
"}")
        self.status.setObjectName("status")
        self.horizontalLayout_3.addWidget(self.status)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.errorMessage = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.errorMessage.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.errorMessage.sizePolicy().hasHeightForWidth())
        self.errorMessage.setSizePolicy(sizePolicy)
        self.errorMessage.setStyleSheet("QLabel{\n"
"    \n"
"    border-radius: 10px;\n"
"    background-color:rgb(236, 66, 69);\n"
"    color: rgb(216, 217, 218);\n"
"    padding-left: auto;\n"
"    padding-right: auto;\n"
"    font: 8pt \"Terminal\";\n"
"    \n"
"}\n"
"QLabel:disabled{\n"
"     background-color:rgba(0, 0, 0, 0);\n"
"    color: rgba(216, 217, 218,0);\n"
"}")
        self.errorMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.errorMessage.setObjectName("errorMessage")
        self.horizontalLayout_3.addWidget(self.errorMessage)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 443, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "Start tracking"))
        self.label.setText(_translate("MainWindow", "Online"))
        self.openPortButton.setText(_translate("MainWindow", "Open Port"))
        self.testButton.setText(_translate("MainWindow", "Test"))
        self.editFolderPath.setText(_translate("MainWindow", "Edit Folder"))
        self.folderPath.setText(_translate("MainWindow", "TextLabel"))
        self.status.setText(_translate("MainWindow", "Status"))
        self.errorMessage.setText(_translate("MainWindow", "Is not picture"))
